import Head from "next/head";
import Link from "next/link";
import { ReactNode, useContext, useState, useEffect } from "react";
import { Store } from "../utils/Store";

type LayoutProps = {
  title?: string;
  children?: ReactNode;
};

const Layout = ({ title, children }: LayoutProps) => {
  const { state, dispatch }: any = useContext(Store);
  const [cartItemCount, setCartItemCount] = useState(0);

  useEffect(() => {
    setCartItemCount(
      state.cart.cartItems.reduce(
        (quantity: number, item: { quantity: number }) =>
          item.quantity + quantity,
        0
      )
    );
  }, [state.cart.cartItems]);

  return (
    <div>
      <Head>
        <title>{title ? `${title} - Amazona` : "Amazona"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col min-h-screen justify-between">
        <header className="p-6 shadow-md">
          <nav className="flex justify-between items-center ">
            <Link href="/" className="text-lg font-bold">
              Amazona
            </Link>
            <div className="space-x-3">
              <Link href="/cart" className="text-lg ">
                Cart{" "}
                {cartItemCount > 0 && (
                  <span className="bg-red-600 text-white text-xs font-bold px-2 py-1 rounded-full">
                    {cartItemCount}
                  </span>
                )}
              </Link>
              <Link href="/login" className="text-lg ">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          <p>Copyright &copy; 2023 Amazona</p>
        </footer>
      </div>
    </div>
  );
};

export default Layout;
